config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tasks#index"

  resources :tasks do
    get :assigned, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  belongs_to :assignee, class_name: 'User', optional: true
  belongs_to :assigner, class_name: 'User', optional: true

  validates_presence_of :title, :status, :creator_id

  enum status: { pending: 'pending', in_progress: 'in progress', completed: 'completed' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_uniqueness_of :email
  validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :destroy, :edit, :update]

  def index
    @grid = ::TasksGrid.new(params[:tasks_grid]) do |scope|
      scope.where(creator: current_user, assignee: nil, assigner: nil).or(scope.where(assignee: current_user))
    end
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params.merge(creator: current_user))

    if task.save
      redirect_to task, notice: 'Task created'
    else
      redirect_to new_task_path, alert: task.errors.full_messages.join('; ')
    end
  end

  def show
  end

  def destroy
    @task.destroy!
    redirect_to tasks_path
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task updated'
    else
      render :edit, alert: @task.errors.full_messages.join('; ')
    end
  end

  def assigned
    @grid = ::TasksGrid.new(params[:tasks_grid]) do |scope|
      scope.where(assigner: current_user)
    end
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :status, :creator_id, :assignee_id, :assigner_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/datagrid/_enum_checkboxes.html.erb
<%# 
Indent in this file may cause extra space to appear.
You can add indent if whitespace doesn't matter for you
%>
<%- elements.each do |value, text, checked| -%>
<%- id = [form.object_name, filter.name, value].join('_').underscore -%>
<%= form.label filter.name, options.merge(for: id) do -%>
<%= form.check_box(filter.name, {multiple: true, id: id, checked: checked, include_hidden: false}, value.to_s, nil) -%>
<%= text -%>
<%- end -%>
<%- end -%>

app/views/datagrid/_form.html.erb
<%= form_for grid, options do |f| -%>
  <div class='d-flex align-items-end gap-2'>
    <% grid.filters.each do |filter| %>
      <div class="datagrid-filter filter">
        <%= f.datagrid_label filter, class: 'form-label' %>
        <%= f.datagrid_filter filter, class: 'form-control' %>
      </div>
    <% end %>
    <div class="datagrid-actions d-flex gap-2">
      <%= f.submit I18n.t("datagrid.form.search").html_safe, class: "datagrid-submit btn btn-success form-control" %>
      <%# https://github.com/rails/rails/pull/14949 -%>
      <%= link_to I18n.t('datagrid.form.reset').html_safe, url_for(grid.to_param => {}), class: "datagrid-reset btn btn-secondary form-control" %>
    </div>
  </div>
<% end -%>

app/views/datagrid/_head.html.erb
<tr>
  <% grid.html_columns(*options[:columns]).each do |column| %>
    <th class="<%= datagrid_column_classes(grid, column) %>">
      <div class='d-flex'>
        <%= column.header %>
        <%= datagrid_order_for(grid, column, options) if column.supports_order? && options[:order]%>
      </div>
    </th>
  <% end %>
</tr>

app/views/datagrid/_order_for.html.erb
<div class="order">
  <%= link_to(
      I18n.t("datagrid.table.order.asc").html_safe,
      datagrid_order_path(grid, column, false),
      class: "asc") %>
  <%= link_to(
      I18n.t("datagrid.table.order.desc").html_safe,
      datagrid_order_path(grid, column, true),
      class: "desc") %>
</div>

app/views/datagrid/_range_filter.html.erb
<%= form.datagrid_filter_input(filter, **from_options) %>
<span class="separator <%= filter.type %>"><%= I18n.t('datagrid.filters.range.separator') %></span>
<%= form.datagrid_filter_input(filter, **to_options) %>

app/views/datagrid/_row.html.erb
<tr>
  <% grid.html_columns(*options[:columns]).each do |column| %>
    <td class="<%= datagrid_column_classes(grid, column) %>"><%= datagrid_value(grid, column, asset) %></td>
  <% end %>
</tr>

app/views/datagrid/_table.html.erb
<%#
Local variables:
* grid - instance of Datagrid
* assets - Array of database Entities
* options - passed options Hash
%>
<% if grid.html_columns(*options[:columns]).any? %>
  <%= content_tag :table, { class: ["table", "table-hover"] } do %>
    <thead>
      <%= datagrid_header(grid, options) %>
    </thead>
    <tbody>
      <% if assets.any? %>
        <%= datagrid_rows(grid, assets, **options) %>
      <% else %>
        <tr><td class="noresults" colspan="100%"><%= I18n.t('datagrid.no_results').html_safe %></td></tr>
      <% end %>
    </tbody>
  <% end %>
<% else -%>
  <%= I18n.t("datagrid.table.no_columns").html_safe %>
<% end %>

app/views/layouts/_actionbar.html.slim
- if user_signed_in?
  .actionbar
    .container-fluid
      .btn-toolbar.actions
        .btn-group
          = yield :actions
      ol.breadcrumb
        = yield :navicrumbs

app/views/layouts/_flash_messages.html.slim
.flash-messages
  - bootstrap_mapping = { 'notice' => :success, 'alert' => :danger }
  - flash.each do |key, value|
    - if ['notice', 'alert'].include?(key) && value.present?
      div( class="alert alert-#{bootstrap_mapping[key]} alert-dismissible fade show" role='alert' )
        = value
        button.btn-close type="button" data-bs-dismiss="alert" aria-label="Close"

app/views/layouts/_navbar.html.slim
nav.navbar.bg-body-tertiary
  .container-fluid
    a.navbar-brand href='/' Task Manager
    - if user_signed_in?
      .dropdown
        .dropdown-toggle(href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false") #{current_user.email}
        ul.dropdown-menu
          li = link_to 'Assigned tasks', assigned_tasks_path, class: 'dropdown-item'
          li = link_to 'Log out', destroy_user_session_path, class: 'dropdown-item', data: { turbo_method: :delete }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/actionbar' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_assign_modal.html.slim
.modal.fade#assignModal tabindex="-1" aria-labelledby="assignModalLabel" aria-hidden="true"
  .modal-dialog
    .modal-content
      = form_with model: @task do |f|
        .modal-header
          h1.modal-title.fs-5#assignModalLabel Assign to user
          button.btn-close type="button" data-bs-dismiss="modal" aria-label="Close"
        .modal-body
          = f.hidden_field :assigner_id, value: current_user.id
          = f.collection_select :assignee_id, User.where.not(id: current_user.id).order(:email), :id, :email, {}, class: 'form-select', required: true
        .modal-footer
          = f.submit 'Submit', class: 'btn btn-success form-control'

app/views/tasks/_form.html.slim
.form.mt-5
  = form_with model: @task do |f|
    = f.label :title, 'Title', class: 'form-label'
    = f.text_field :title, class: 'form-control', required: true

    = f.label :description, 'Description', class: 'form-label'
    = f.text_area :description, class: 'form-control'

    = f.label :status, 'Status', class: 'form-label'
    = f.select :status, ['pending', 'in progress', 'completed'], { required: true }, class: 'form-select'

    = f.label :due_date, 'Due date', class: 'form-label'
    = f.date_field :due_date, class: 'form-control'

    = f.submit 'Submit', class: 'btn btn-success form-control mt-3'
    = link_to 'Cancel', root_path, class: 'btn btn-secondary form-control mt-3'

app/views/tasks/_tasks_grid.html.slim
.container-fluid
  = datagrid_form_for @grid, method: :get, url: path
  = datagrid_table @grid

app/views/tasks/assigned.html.slim
- provide :navicrumbs do
  li.breadcrumb-item.active = 'Assigned tasks'

= render 'tasks_grid', path: assigned_tasks_path

app/views/tasks/edit.html.slim
- provide :navicrumbs do
  li.breadcrumb-item = link_to 'Tasks', root_path
  li.breadcrumb-item = link_to @task.title, task_path(@task)
  li.breadcrumb-item.active = 'Edit'

= render 'form'

app/views/tasks/index.html.slim
- provide :actions do
  = link_to 'Create task', new_task_path, class: 'btn btn-primary'

= render 'tasks_grid', path: tasks_path

app/views/tasks/new.html.slim
- provide :navicrumbs do
  li.breadcrumb-item = link_to 'Tasks', root_path
  li.breadcrumb-item.active = 'New'

= render 'form'

app/views/tasks/show.html.slim
- provide :navicrumbs do
  li.breadcrumb-item = link_to 'Tasks', root_path
  li.breadcrumb-item.active = @task.title

- provide :actions do
  - if @task.assignee == current_user || (@task.creator == current_user && @task.assignee.nil? && @task.assigner.nil?)
    = link_to 'Delete', task_path(@task), class: 'btn btn-danger float-end', data: { turbo_confirm: 'Do you really want to delete?', turbo_method: :delete }
    = link_to 'Edit', edit_task_path(@task), class: 'btn btn-primary float-end'
    .btn.btn-secondary.float-end(data-bs-toggle='modal' data-bs-target='#assignModal') = 'Assign'

.mt-3.ms-5
  h1 Task details

  = show_for @task do |a|
    = a.attribute :title
    = a.attribute :description
    = a.attribute :due_date
    = a.attribute :status
    = a.association :creator, using: :email
    = a.association :assignee, using: :email
    = a.association :assigner, using: :email

= render 'assign_modal'